# Generated by Django 2.0.3 on 2018-03-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRUE_NAME', models.CharField(default='NONAME', max_length=100)),
                ('FILE_NAME', models.CharField(default='NONAME', max_length=100)),
                ('GEXF_LINK', models.TextField(default='NOGEXF')),
                ('FILE_LINK', models.TextField(default='NOFILE')),
            ],
        ),
    ]
