# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappings',
            name='FILE_LINK',
            field=models.TextField(default='NOFILE'),
        ),
        migrations.AddField(
            model_name='mappings',
            name='FILE_NAME',
            field=models.CharField(default='NONAME', max_length=100),
        ),
        migrations.AddField(
            model_name='mappings',
            name='TRUE_NAME',
            field=models.CharField(default='NONAME', max_length=100),
        ),
    ]
