# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20180216_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappings',
            name='GEXF_LINK',
            field=models.TextField(default='NOGEXF'),
        ),
    ]
